#! /bin/sh

TST=${1:-tst}

for i in $TST/*.tst
do
    echo $i
    basen=`basename $i .tst`
    cabal run cpsa4db -- -o $TST/$basen.db $i
    cabal run cpsa4dbprolog $TST/$basen.db | sort > $TST/$basen.pl
done    
