#! /bin/sh

for f in *.tst
do
    b=`basename $f .tst`
    echo graphing $f
    ../dist/build/cpsa4graph/cpsa4graph -o "${b}_tst.xhtml" "$f"
    ../dist/build/cpsa4shapes/cpsa4shapes "$f" | \
	../dist/build/cpsa4graph/cpsa4graph -o "${b}_tst_shapes.xhtml"
done
