#! /bin/sh
PROG="time ../dist/build/cpsa/cpsa"
ARGS="-b 12 -l 200000 -o /dev/null nsl5resp3.lisp"
CPUS="1 2 3 4 5 6 14"
for i in $CPUS
do
  echo $PROG +RTS -N$i -RTS $ARGS
  $PROG +RTS -N$i -RTS $ARGS
  echo
done
