(herald wrap-decrypt)

(comment "CPSA 2.4.0")
(comment "All input read from wrap_decrypt.lsp")

(defprotocol wrap-decrypt basic
  (defrole make
    (vars (k skey))
    (trace (sync (cat "make" (hash k))) (send (hash k)))
    (pen-non-orig k))
  (defrole set-wrap
    (vars (k skey))
    (trace (sync (cat "set-wrap" (hash k)))))
  (defrole set-decrypt
    (vars (k skey))
    (trace (sync (cat "set-decrypt" (hash k)))))
  (defrole wrap
    (vars (k0 k1 skey))
    (trace (recv (hash k0)) (recv (hash k1))
      (sync (cat "wrap" (hash k0) (hash k1))) (send (enc k0 k1))))
  (defrole decrypt
    (vars (x mesg) (k skey))
    (trace (recv (enc x k)) (recv (hash k))
      (sync (cat "decrypt" (hash k))) (send x))))

(defskeleton wrap-decrypt
  (vars (k skey))
  (deflistener k)
  (defstrand make 2 (k k))
  (defstrand wrap 4 (k0 k) (k1 k))
  (defstrand decrypt 4 (x k) (k k))
  (precedes ((1 1) (2 0)) ((2 3) (3 0)) ((3 3) (0 0)))
  (pen-non-orig k)
  (comment "desired shape")
  (traces ((recv k) (send k))
    ((sync (cat "make" (hash k))) (send (hash k)))
    ((recv (hash k)) (recv (hash k))
      (sync (cat "wrap" (hash k) (hash k))) (send (enc k k)))
    ((recv (enc k k)) (recv (hash k)) (sync (cat "decrypt" (hash k)))
      (send k)))
  (label 0)
  (unrealized)
  (shape)
  (maps ((0 1 2 3) ((k k))))
  (origs))

(comment "Nothing left to do")

(defprotocol wrap-decrypt basic
  (defrole make
    (vars (k skey))
    (trace (sync (cat "make" (hash k))) (send (hash k)))
    (pen-non-orig k))
  (defrole set-wrap
    (vars (k skey))
    (trace (sync (cat "set-wrap" (hash k)))))
  (defrole set-decrypt
    (vars (k skey))
    (trace (sync (cat "set-decrypt" (hash k)))))
  (defrole wrap
    (vars (k0 k1 skey))
    (trace (recv (hash k0)) (recv (hash k1))
      (sync (cat "wrap" (hash k0) (hash k1))) (send (enc k0 k1))))
  (defrole decrypt
    (vars (x mesg) (k skey))
    (trace (recv (enc x k)) (recv (hash k))
      (sync (cat "decrypt" (hash k))) (send x))))

(defskeleton wrap-decrypt
  (vars (k skey))
  (deflistener k)
  (defstrand make 2 (k k))
  (pen-non-orig k)
  (traces ((recv k) (send k))
    ((sync (cat "make" (hash k))) (send (hash k))))
  (label 1)
  (unrealized (0 0))
  (origs)
  (comment "1 in cohort - 1 not yet seen"))

(defskeleton wrap-decrypt
  (vars (k k1 skey))
  (deflistener k)
  (defstrand make 2 (k k))
  (defstrand wrap 4 (k0 k) (k1 k1))
  (precedes ((2 3) (0 0)))
  (pen-non-orig k)
  (operation nonce-test (added-strand wrap 4) k (0 0))
  (traces ((recv k) (send k))
    ((sync (cat "make" (hash k))) (send (hash k)))
    ((recv (hash k)) (recv (hash k1))
      (sync (cat "wrap" (hash k) (hash k1))) (send (enc k k1))))
  (label 2)
  (parent 1)
  (unrealized (2 0))
  (comment "1 in cohort - 1 not yet seen"))

(defskeleton wrap-decrypt
  (vars (k k1 skey))
  (deflistener k)
  (defstrand make 2 (k k))
  (defstrand wrap 4 (k0 k) (k1 k1))
  (deflistener k)
  (precedes ((2 3) (0 0)) ((3 1) (2 0)))
  (pen-non-orig k)
  (operation encryption-test (added-listener k) (hash k) (2 0))
  (traces ((recv k) (send k))
    ((sync (cat "make" (hash k))) (send (hash k)))
    ((recv (hash k)) (recv (hash k1))
      (sync (cat "wrap" (hash k) (hash k1))) (send (enc k k1)))
    ((recv k) (send k)))
  (label 3)
  (parent 2)
  (unrealized (3 0))
  (comment "1 in cohort - 1 not yet seen"))

(defskeleton wrap-decrypt
  (vars (k k1 k1-0 skey))
  (deflistener k)
  (defstrand make 2 (k k))
  (defstrand wrap 4 (k0 k) (k1 k1))
  (deflistener k)
  (defstrand wrap 4 (k0 k) (k1 k1-0))
  (precedes ((2 3) (0 0)) ((3 1) (2 0)) ((4 3) (3 0)))
  (pen-non-orig k)
  (operation nonce-test (added-strand wrap 4) k (3 0))
  (traces ((recv k) (send k))
    ((sync (cat "make" (hash k))) (send (hash k)))
    ((recv (hash k)) (recv (hash k1))
      (sync (cat "wrap" (hash k) (hash k1))) (send (enc k k1)))
    ((recv k) (send k))
    ((recv (hash k)) (recv (hash k1-0))
      (sync (cat "wrap" (hash k) (hash k1-0))) (send (enc k k1-0))))
  (label 4)
  (parent 3)
  (unrealized (4 0))
  (comment "1 in cohort - 1 not yet seen"))

(defskeleton wrap-decrypt
  (vars (k k1 k1-0 skey))
  (deflistener k)
  (defstrand make 2 (k k))
  (defstrand wrap 4 (k0 k) (k1 k1))
  (deflistener k)
  (defstrand wrap 4 (k0 k) (k1 k1-0))
  (deflistener k)
  (precedes ((2 3) (0 0)) ((3 1) (2 0)) ((4 3) (3 0)) ((5 1) (4 0)))
  (pen-non-orig k)
  (operation encryption-test (added-listener k) (hash k) (4 0))
  (traces ((recv k) (send k))
    ((sync (cat "make" (hash k))) (send (hash k)))
    ((recv (hash k)) (recv (hash k1))
      (sync (cat "wrap" (hash k) (hash k1))) (send (enc k k1)))
    ((recv k) (send k))
    ((recv (hash k)) (recv (hash k1-0))
      (sync (cat "wrap" (hash k) (hash k1-0))) (send (enc k k1-0)))
    ((recv k) (send k)))
  (label 5)
  (parent 4)
  (unrealized (5 0))
  (comment "1 in cohort - 1 not yet seen"))

(defskeleton wrap-decrypt
  (vars (k k1 k1-0 k1-1 skey))
  (deflistener k)
  (defstrand make 2 (k k))
  (defstrand wrap 4 (k0 k) (k1 k1))
  (deflistener k)
  (defstrand wrap 4 (k0 k) (k1 k1-0))
  (deflistener k)
  (defstrand wrap 4 (k0 k) (k1 k1-1))
  (precedes ((2 3) (0 0)) ((3 1) (2 0)) ((4 3) (3 0)) ((5 1) (4 0))
    ((6 3) (5 0)))
  (pen-non-orig k)
  (operation nonce-test (added-strand wrap 4) k (5 0))
  (traces ((recv k) (send k))
    ((sync (cat "make" (hash k))) (send (hash k)))
    ((recv (hash k)) (recv (hash k1))
      (sync (cat "wrap" (hash k) (hash k1))) (send (enc k k1)))
    ((recv k) (send k))
    ((recv (hash k)) (recv (hash k1-0))
      (sync (cat "wrap" (hash k) (hash k1-0))) (send (enc k k1-0)))
    ((recv k) (send k))
    ((recv (hash k)) (recv (hash k1-1))
      (sync (cat "wrap" (hash k) (hash k1-1))) (send (enc k k1-1))))
  (label 6)
  (parent 5)
  (unrealized (6 0))
  (comment "1 in cohort - 1 not yet seen"))

(comment "Strand bound exceeded--aborting run")

(defskeleton wrap-decrypt
  (vars (k k1 k1-0 k1-1 skey))
  (deflistener k)
  (defstrand make 2 (k k))
  (defstrand wrap 4 (k0 k) (k1 k1))
  (deflistener k)
  (defstrand wrap 4 (k0 k) (k1 k1-0))
  (deflistener k)
  (defstrand wrap 4 (k0 k) (k1 k1-1))
  (deflistener k)
  (precedes ((2 3) (0 0)) ((3 1) (2 0)) ((4 3) (3 0)) ((5 1) (4 0))
    ((6 3) (5 0)) ((7 1) (6 0)))
  (pen-non-orig k)
  (operation encryption-test (added-listener k) (hash k) (6 0))
  (traces ((recv k) (send k))
    ((sync (cat "make" (hash k))) (send (hash k)))
    ((recv (hash k)) (recv (hash k1))
      (sync (cat "wrap" (hash k) (hash k1))) (send (enc k k1)))
    ((recv k) (send k))
    ((recv (hash k)) (recv (hash k1-0))
      (sync (cat "wrap" (hash k) (hash k1-0))) (send (enc k k1-0)))
    ((recv k) (send k))
    ((recv (hash k)) (recv (hash k1-1))
      (sync (cat "wrap" (hash k) (hash k1-1))) (send (enc k k1-1)))
    ((recv k) (send k)))
  (label 7)
  (parent 6)
  (unrealized (7 0))
  (comment "aborted"))
